image:
  file: .gitpod/Dockerfile
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
vscode:
  extensions:
    - ligolang-publish.ligo-vscode@0.4.11
    - baking-bad.michelson@0.1.0
    - serokell-io.michelson-debugger@0.1.1
tasks:
  - openMode: tab-after
    command: |
      until open README.md ; do sleep 1; done
      clear
